name: blog_html_builder
description: Package containing helpers to build stringified HTML for blog posts.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  blog_models:
    path: ../blog_models
  intl: ^0.19.0
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
